version: "3.7"

services:
  web_check:
    image: nginx:latest
    container_name: web_check
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./api:/api
      - .nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - checker
    networks:
      - test_dbs_network
  checker:
    build: ./api
    container_name: checker
    restart: always
    volumes:
      - ./api:/api
    networks:
      - test_dbs_network

networks:
  test_dbs_network:
    name: test_dbs_network
