CREATE TABLE IF NOT EXISTS USERS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD    VARCHAR(64)        NOT NULL,
    IS_EXISTS   BOOLEAN,
    STATE       TINYINT(1)         NOT NULL,
    DESCRIPTION VARCHAR(20),
    IP_RIGHTS   VARCHAR(200),
    DATE_TO     DATE               NOT NULL
    );

ALTER TABLE USERS
    COMMENT 'test table for users';

ALTER TABLE USERS
    MODIFY USERNAME VARCHAR(20) NOT NULL
    COMMENT 'user username)';