version: '3.7'

services:
  test_oracle:
    image: gvenzl/oracle-xe:21-faststart
    container_name: test_oracle
    volumes:
      - ./settings/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    environment:
      - ORACLE_PASSWORD=Oracle_secret1
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - test_dbs_network

networks:
  test_dbs_network:
    name: test_dbs_network
