version: '3.7'

services:
  test_postgresql:
    image: postgres:14.1
    container_name: test_postgresql
    volumes:
      - ".data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=public
    restart: always
    networks:
      - test_dbs_network

networks:
  test_dbs_network:
    name: test_dbs_network