version: '3.7'

services:
  test_mariaDB:
    image: mariadb:10.8.3
    container_name: test_mariaDB
    volumes:
      - ./settings/server.cnf:/etc/mysql/conf.d/server.cnf
      - ./settings/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
      - ./settings/02-init.sql:/docker-entrypoint-initdb.d/02-init.sql
    ports:
      - "13306:3306"
    restart: always
    environment:
      TZ: "Europe/Kiev"
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: TEST_SCHEMA
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - test_dbs_network

networks:
  test_dbs_network:
    name: test_dbs_network
