
alter session set container = XEPDB1;
CREATE USER DEV_USER IDENTIFIED BY "password!";
GRANT CONNECT TO DEV_USER;
CREATE USER ADMIN IDENTIFIED BY ADMIN;
GRANT CONNECT, RESOURCE, DBA TO ADMIN;
CREATE USER TEST_S_1 IDENTIFIED BY "TEST_S_1";
ALTER USER TEST_S_1 QUOTA unlimited ON SYSTEM;
CREATE TABLESPACE TEST_AGG DATAFILE 'TEST_AGG_data.dbf'  SIZE 10m;


CREATE USER TEST_S_2;

CREATE TABLE TEST_S_2.CASES (
	TICKET_ID NUMBER NULL,
	STATUS VARCHAR2(255) NULL,
	OPEN_DATE DATE NULL
);


GRANT ALL PRIVILEGES TO ADMIN;
GRANT ALL PRIVILEGES TO DEV_USER;

ALTER USER TEST_S_1 quota unlimited on USERS;
ALTER USER TEST_S_2 quota unlimited on USERS;

GRANT UNLIMITED TABLESPACE TO ADMIN;
